CREATE SCHEMA Datalake;

DROP TABLE IF EXISTS Datalake.Test1
CREATE TABLE Datalake.Test1
(
COLUMNONE INT NULL
,COLUMNTWO INT NULL
,COLUMNTHREE INT NULL
)


DROP TABLE IF EXISTS Datalake.Test2
CREATE TABLE Datalake.Test2
(
COLUMNONE INT NULL
,COLUMNTWO INT NULL
,COLUMNTHREE INT NULL
)

